# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(email: 'admin@localhost.com', password: 'admin123456', :password_confirmation => 'admin123456', role: 'admin', storeCode: 'I905', branchCode: '1706')
User.create(email: 'admin@italtile.co.za', password: 'password', role: 'comadmin', storeCode: 'I905', branchCode: '1706')
User.create(email: 'com@italtile.co.za', password: 'password', role: 'com', storeCode: 'I905', branchCode: '1706')
User.create(email: 'shop@italtile.co.za', password: 'password', role: 'shop', storeCode: 'I905', branchCode: '1706')
User.create(email: 'motaunge@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '91', fullName: 'Evelyn Motaung')
User.create(email: 'legodis@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '96', fullName: 'Sandy Legodi')
User.create(email: 'britzj@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '1706', fullName: 'Jaco Britz')
User.create(email: 'goliathm@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '5024', fullName: 'Marshall Goliath')
User.create(email: 'humans@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '5324', fullName: 'Sias Human')
User.create(email: 'vanvuurens@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '5361', fullName: 'Samantha Van Vuuren')
User.create(email: 'mchunum@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I902', branchCode: '5461', fullName: ' Makha Mchunu')
User.create(email: 'brennerw@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '1562', fullName: 'Wayne Brenner')
User.create(email: 'lukusae@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '2131', fullName: 'Elijah M Lukusa')
User.create(email: 'pietersee@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '4018', fullName: 'Erik Pieterse')
User.create(email: 'letsholoc@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '4855', fullName: 'Christopher Letsholo')
User.create(email: 'baloyik@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '5119', fullName: 'Katekani Baloyi')
User.create(email: 'duplessisj@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '5418', fullName: 'Jan-Harm Du Plessis')
User.create(email: 'mphamub@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I905', branchCode: '5419', fullName: 'Brenda Mphamu')
User.create(email: 'pillaym@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I916', branchCode: '2611', fullName: ' Mark Pillay')
User.create(email: 'lockharta@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I916', branchCode: '4246', fullName: ' Andrew Lockhart')
User.create(email: 'jacobse@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I916', branchCode: '5318', fullName: ' Elize Jacobs')
User.create(email: 'ndlovuq@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I916', branchCode: '5336', fullName: ' Queen Ndlovu')
User.create(email: 'ngubanen@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '3486', fullName: ' Nomvula Ngubane')
User.create(email: 'sonof@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '5003', fullName: ' Floyd Sono')
User.create(email: 'tikanet@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '5039', fullName: ' Tracy Tikane')
User.create(email: 'makhadit@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '5394', fullName: ' Twiggy Makhadi')
User.create(email: 'bassonu@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '5508', fullName: ' Uraaz Basson')
User.create(email: 'pretoriusg@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I918', branchCode: '5317', fullName: 'Gerhard Pretorius')
User.create(email: 'singhn@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '999', fullName: ' Neeta Singh')
User.create(email: 'stemmetl@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '4165', fullName: ' Lomea Stemmet')
User.create(email: 'munilala@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '4242', fullName: ' Aisha Munilal')
User.create(email: 'nadrajahn@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '4291', fullName: ' Kuven Nadrajah')
User.create(email: 'naidooc@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '4466', fullName: ' Clint Naidoo')
User.create(email: 'bennettw@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '4901', fullName: ' Wayne Bennett')
User.create(email: 'pillayr@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '5507', fullName: ' Reagan Pillay')
User.create(email: 'parking@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '5527', fullName: ' Gregory Parkin')
User.create(email: 'groeningenn@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '5665', fullName: ' Nicole Van Groeningen')
User.create(email: 'abrahamsm@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I913', branchCode: '5666', fullName: ' Malcolm Abrahams')
User.create(email: 'ngutshanim@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I914', branchCode: '3482', fullName: ' Miranda Ngutshani')
User.create(email: 'mathabas@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I914', branchCode: '4433', fullName: ' Senzo Mathaba')
User.create(email: 'mabuzaz@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I914', branchCode: '4819', fullName: ' Zinhle Mabuza')
User.create(email: 'veigam@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I914', branchCode: '5618', fullName: ' Monica Veiga')
User.create(email: 'fieldc@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '116', fullName: ' Cindy Field')
User.create(email: 'vjaarsveldf@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '2327', fullName: ' Frans Van Jaarsveld')
User.create(email: 'klaaser@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '3388', fullName: ' Roelien Klaase')
User.create(email: 'schatza@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '3472', fullName: ' Ashwin Schatz')
User.create(email: 'lombardh@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '4167', fullName: ' Heidi  Lombard')
User.create(email: 'jordaane@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I915', branchCode: '5367', fullName: ' Etienne Jordaan')
User.create(email: 'janm@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '294', fullName: ' Melvyn Jansen')
User.create(email: 'tinahr@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '348', fullName: ' Tinah Smith')
User.create(email: 'chettyp@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '955', fullName: ' Gus Chetty')
User.create(email: 'kemperj@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '1067', fullName: ' Johan Kemper')
User.create(email: 'ismailc@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '2391', fullName: ' Clint Ismail')
User.create(email: 'hughesc@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '4195', fullName: ' Cindy Hughes')
User.create(email: 'burgerp@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '4544', fullName: ' Pieter Burger')
User.create(email: 'coetzeem@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '4929', fullName: ' Melanie Coetzee')
User.create(email: 'dutoith@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '4993', fullName: ' Hilani Du Toit')
User.create(email: 'basinig@italtile.co.za', password: 'password', role: 'retail', training_mode: '0', storeCode: 'I917', branchCode: '5504', fullName: ' Gwen Basini')
User.create(email: 'mariusm@italtile.co.za', password: 'password', role: 'comadmin', training_mode: '0', storeCode: 'I931', branchCode: '3865', fullName: ' Marius Maree')
User.create(email: 'tanjah@italtile.co.za', password: 'password', role: 'comadmin', training_mode: '0', storeCode: 'I931', branchCode: '4304', fullName: ' Tanja Herselman')
User.create(email: 'albertsh@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '4584', fullName: ' Henry Alberts')
User.create(email: 'brownc@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '4984', fullName: ' Catherine Brown')
User.create(email: 'pretoriusw@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '5378', fullName: ' Willie Pretorius')
User.create(email: 'vandenbergv@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '5474', fullName: 'Victor van den Berg')
User.create(email: 'burgerp@italtile.co.za', password: 'password', role: 'commercial', training_mode: '0', storeCode: 'I931', branchCode: '4920', fullName: 'Pieter Burger')
User.create(email: 'munros@italtile.co.za', password: 'password', role: 'admin', training_mode: '0', storeCode: 'I931', branchCode: '5155', fullName: 'Susan Munro')
User.create(email: 'myburghl@italtile.co.za', password: 'password', role: 'admin', training_mode: '0', storeCode: 'IW01', branchCode: '3626', fullName: 'Lauren Myburgh')
Storeaddress.create(storecode: 'I902', head: 'Italtile Pretoria', line1: 'Palala Road, Pretoria East, Menlyn', line2:'Telephone - 012 348 8700', line3:'Fax - 012 348 3429', line4:'PO BOX 35232, Menlo Park, 0102', line5:'VAT Registration: 4340256116', line6:'Company Registration: 2007/016836/076')
Storeaddress.create(storecode: 'I905', head: 'Italtile Bryanston', line1: 'Corner William Nicol and Peter Place, Bryanston', line2:'Telephone - 011 510 9002/3/4/5', line3:'Fax - 011 510 9019', line4:'PO BOX 1689, Randburg, 2125', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'IW01', head: 'Italtile Bryanston', line1: 'Corner William Nicol and Peter Place, Bryanston', line2:'Telephone - 011 510 9002/3/4/5', line3:'Fax - 011 510 9019', line4:'PO BOX 1689, Randburg, 2125', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I916', head: 'Italtile Boksburg', line1: 'Corner Jan Smuts and Loizides Avenue, Bardene,Boksburg', line2:'Telephone - 011 255 1060', line3:'Fax - 011 255 1068', line4:'Email - italtileboksburg@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I918', head: 'Italtile The Glen ', line1: '6 Skukusa Road,Johannesburg South', line2:'Telephone - 011 027 7900', line3:'Fax - 086 623 3683', line4:'Email - Italumgbm@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I913', head: 'Italtile Umhlanga', line1: '7 Tetford Crescent, Umhlanga Ridge,Umhlanga', line2:'Telephone -  031 566 5069', line3:'Fax - 031 566 5090', line4:'Email - Italumgbm@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I914', head: 'Italtile Nelspruit', line1: 'Oewer Street, Riverside,Nelspruit', line2:'Telephone - 013 752 8333', line3:'Fax - 013 735 3362', line4:'Email - italnspbm@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I915', head: 'Italtile Somerset West', line1: 'Corner N2 and R44, Next To Somerset Mall,Somerset West', line2:'Telephone - 021 851 2170 ', line3:'Fax - 021 852 7790', line4:'Email - italsswbm@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I917', head: 'Italtile Cape Town', line1: 'Gold Street,Northgate Estate, Brooklyn, Cape Town', line2:'Telephone - 021 510 7766', line3:'Fax - 021 510 7788', line4:'Email - italctnbm@italtile.co.za', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')
Storeaddress.create(storecode: 'I931', head: 'Italtile Commercial', line1: '38 Palala Road, Ashlea Gardens, Menlyn, Pretoria', line2:'Telephone - 012 348 8700', line3:'Fax - 012 348 3429', line4:'Email -', line5:'VAT Registration: 4840245445', line6:'Company Registration: 2007/016836/07')




#AdminUser.create(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')
